config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :posts, only: [:new, :create, :show, :edit, :update, :like, :destroy]
  resources :posts do
    resources :comments
  end
  devise_for :users
  resources :users
  get 'posts/new', to: 'posts#new', as: 'new'
  get 'home/index', to: 'home#index', as: 'home'
  post 'posts', to: 'posts#create'
  patch 'like', to: 'posts#like', as: 'like'
  patch 'edit', to: 'posts#edit', as: 'edit'
  delete 'posts/delete/:id', to: 'posts#destroy', as: 'destroy'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_attached_file :image, :styles =>  {
			:thumb => "100x100#",
			:small  => "150x150>",
			:medium => "300x300" },
	                  url: "/system/:hash.:extension",
	                  hash_secret: "abc123"

	validates_attachment_presence :image
	validates_attachment_size :image, :less_than => 5.megabytes
	validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
	validates :likes, :user_id, :caption, presence: true
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up){ |u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update){ |u| u.permit(:name, :email, :password, :password_confirmation) }
  end

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path, :notice => 'Please sign in to continue'
    end
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
	  @post = Post.find(params[:post_id])
	 # @comment = @post.comments.new(params[:comment])
	  @comment = @post.comments.create!(params.require(:comment).permit(:body))
	  @comment.commenter = current_user.name
	 # @comment.commenter = "Niha"
	 # @comment.user_id = current_user.id
	  @comment.save
	  redirect_to(:back)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authenticate_user!

  	def index
    	@posts = Post.order('created_at')
 	end

    def show
    	@post = Post.find(params[:id])
  	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:success] = "The photo was added!"
			redirect_to root_path
		else
			render 'new'
		end
	end

	private

	def post_params
		params.require(:post).permit(:image, :caption)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authenticate_user!
  	def index
    	@posts = Post.order('created_at')
 	end

    def show
    	@post = Post.find(params[:id])
  	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.likes = 0
		@post.user = current_user
		#@post.comments = Array.new
		if @post.save
			flash[:success] = "The photo was added!"
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post.update(post_params)
		redirect_to user_path(id: @post.user_id)
	end

	def like
		@post = Post.find(params[:id])
		@post.update_column(:likes, @post.likes + 1)
		@post.save
		redirect_to user_path(id: @post.user_id)
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		@post.save
		redirect_to user_path(id: @post.user_id)
	end

	private

	def post_params
		params.require(:post).permit(:image, :caption)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token
	before_filter :authenticate_user!

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->

<div class="mbr-section__container mbr-section__container--isolated container" style="padding-top: 200px">
  <div class="row">
    <div class="mbr-box mbr-box--fixed mbr-box--adapted">
      <div class="mbr-box__magnet mbr-box__magnet--top-right mbr-section__left col-sm-6" style="padding-left: 200px">

        <% @top = Post.new %>
        <% if @posts %>
            <% @top = @posts.first %>
            <% @posts.each do |post| %>
                <% if post.likes > @top.likes %>
                    <% @top = post %>
                <% end %>
            <% end %>
        <% end %>
        <% if @top != NIL%>
            <br/>
            <%= link_to image_tag(@top.image(:medium), class: 'media-object'), "users/#{@top.user_id}", target: '/' %>
            <h4>Featuring <%= @top.caption %> with a whopping <%= @top.likes %> likes! </h4>
            <br/>
            <h4>Add a comment:</h4>
            <%= form_for([@top, @top.comments.build]) do |f| %>
              <div class="field">
                <%= f.label :body %><br />
                <%= f.text_area :body %>
              </div>
              <div class="actions">
                <%= f.submit %>
              </div>
            <% end %>
            <br/>
          <% if @top.comments.first.body == NIL %>
          <h4>Comments:</h4>
          <p> No comments yet :( </p>
          <% else %>
          <h4>Comments:</h4>
          <% @top.comments.each do |comment| %>
            <p>
              <h6>
              <%if comment.commenter != NIL %>
                <b><%= comment.commenter %> says:</b>
                "<%= comment.body %>"
              </h6>
              <%end%>
            </p>

          <% end %>
          <% end %>

        <% end %>
      </div>
      <div class="mbr-box__magnet mbr-class-mbr-box__magnet--center-left col-sm-6 mbr-section__right">
        <div class="mbr-section__container mbr-section__container--middle">
          <div class="mbr-header mbr-header--auto-align mbr-header--wysiwyg">
            <h3 class="mbr-header__text">Featuring the Top Dog of Berkeley</h3>

          </div>
        </div>
        <div class="mbr-section__container mbr-section__container--middle">
          <div class="mbr-article mbr-article--auto-align mbr-article--wysiwyg">
            <p>
              Find who's the top dog of Berkeley! The domestic dog (Canis lupus familiaris or Canis familiaris) is a domesticated canid which has been selectively bred for millennia for various behaviors, sensory capabilities, and physical attributes.
            </p>
          </div>
        </div>
        <div class="mbr-section__container">
          <div class="mbr-buttons mbr-buttons--auto-align btn-inverse"><a class="btn btn-lg btn-default" href="/users" target="_blank">To see more dogs</a></div>
        </div>
      </div>

    </div>
  </div>
</div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

      </div>
    </div>
  </div>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <div class="post-preview">

          <h2 class="post-title">
            Now for the other dogs...
          </h2>
          <div class="row">
              <% if @posts %>
                <% @posts.reverse.each do |post| %>
                    <% if post.id != @top.id %>
                      <div class="col-xs-3" style="width: 180px; height: 200px">

                         <%= link_to image_tag(post.image(:small), class: 'media-object'), "users/#{post.user_id}", target: '_blank' %>

                      </div>
                    <% end %>
                    <% end %>
            <% end %>
          </div>
         </div>
      <!-- Pager -->
      <ul class="pager">
        <li class="next">
          <a href="users">Older Posts &rarr;</a>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>BTD</title>

  <!-- CDN Boostrap -->
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css">

  <!-- Custom CSS -->
  <link href="clean-blog.css" rel="stylesheet">
  <link href="clean-blog.min.css" rel="stylesheet">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

  <!-- Custom Fonts -->
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>

  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <title>Proj2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
		<nav class="navbar navbar-default navbar-custom navbar-fixed-top" style="background-color:#019893; height: 100px">
      <div style="background-color: #1a1c42">
        <img src="http://i275.photobucket.com/albums/jj282/miki-teh-demon/banner_zpsefcbakhr.jpg">
      </div>
	  <div class="container-fluid" style="background-color:#019893; max-height: 10px; font-size: 10px">

	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header page-scroll" style="margin-top: -18px">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/" style="color:white; font-size: 10px">
	      	<% if user_signed_in? %>
	      		Welcome, <%= current_user.name%>!
	      	<% else %>
	      		Berkeley's Top Dog
	      	<% end %>
	      </a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" >
	      <ul class="nav navbar-nav navbar-right" style="margin-top: -18px" >
	        <li>
	          <a href="/" style="color:white; font-size: 10px">Home</a>
	        </li>
	        <li>
	        	<% if user_signed_in? %>
		        	<% User.all.each do |user| %>
		        		<% if user.id == current_user.id %>
		        			<%= link_to 'Profile', user, :style=>'color:#FFFFFF; font-size:10px'%>
		        		<% end %>
		        	<% end %>
		        <% end %>
	        </li>
	        <li>
	        	<% if user_signed_in? %>
	        		<%= link_to 'New Post', new_path, :style=>'color:#FFFFFF; font-size:10px' %>
	        	<% end %>
	        </li>
	        <li>
	          <%= link_to 'Users', users_path, :method=>'get', :style=>'color:#FFFFFF; font-size: 10px'%>
	        </li>
	        <li>
	        	<% if user_signed_in? %>
	        		<%= link_to 'Log Out', destroy_user_session_path, :method=>'delete', :style=>'color:#FFFFFF; font-size: 10px' %>
	        	<% else %>
	          	<li><%= link_to 'Log In', new_user_session_path, :style=>'color:#FFFFFF; font-size: 10px' %></li>
	          <% end %>
	        </li>
	      </ul>
	    </div>
	    <!-- /.navbar-collapse -->

	  </div>
	  <!-- /.container -->
	</nav>


	<%= yield %>
<hr>

	<!-- Footer -->
	<footer>
	  <div class="container">
	    <div class="row">
	      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
	        <ul class="list-inline text-center">
	          <li>
	            <a href="#">
	                                <span class="fa-stack fa-lg">
	                                    <i class="fa fa-circle fa-stack-2x"></i>
	                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	                                </span>
	            </a>
	          </li>
	          <li>
	            <a href="#">
	                                <span class="fa-stack fa-lg">
	                                    <i class="fa fa-circle fa-stack-2x"></i>
	                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	                                </span>
	            </a>
	          </li>
	          <li>
	            <a href="#">
	                                <span class="fa-stack fa-lg">
	                                    <i class="fa fa-circle fa-stack-2x"></i>
	                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
	                                </span>
	            </a>
	          </li>
	        </ul>
	        <p class="copyright text-muted">Copyright &copy; BTD</p>
	      </div>
	    </div>
	  </div>
	</footer>

	<!-- jQuery -->
	<script src="jquery.js"></script>

	<!-- Bootstrap Core JavaScript -->
	<script src="bootstrap.min.js"></script>

	<script src="bootstrap.js"></script>

	<!-- Custom Theme JavaScript -->
	<script src="clean-blog.min.js"></script>

	<script src="clean-blog.js"></script>

</body>
</html>

app/views/posts/_post.html.erb
<%= link_to image_tag(post.image(:medium), class: 'media-object'), post.image(:medium), target: '_blank' %>
<h4>"<%= post.caption %>"</h4>
<h4> Likes: <%= post.likes %></h4>
<% if current_user.id != post.user_id || current_user.admin == true %>
	<%= button_to "Like", like_path(id: post.id), :class => "button small", :method => :patch %>
<% end %>
<% if current_user.id == post.user_id || current_user.admin == true %>
	<%= button_to "Edit", edit_path(id: post.id), :class => "button small", :method => :patch %>
	<%= button_to "Delete", destroy_path(id: post.id), :class => "button small", :method => :delete %>
<% end %>

app/views/posts/edit.html.erb
<div class="col-md-12" style="margin-top:100px">
  <div id="loginModal" class="modal show" style="position:relative; overflow:auto;">
    <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
            <h1>Edit Caption</h1>

            <%= form_for @post do |f| %>
              <%= render 'shared/errors', object: @post %>

              <p>
                <%= f.label :caption %>
                <%= f.text_field :caption %>
              </p>

              <%= f.submit 'Save changes' %>
              <%= button_to 'Cancel', home_path(), :class => "button medium", :method => :get %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="col-md-12" style="margin-top:100px">
  <div id="loginModal" class="modal show" style="position:relative; overflow:auto;">
    <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
            <h1>Upload Photo</h1>

            <%= form_for @post do |f| %>
              <%= render 'shared/errors', object: @post %>

              <p>
                <%= f.label :caption %>
                <%= f.text_field :caption %>
              </p>

              <p>
                <%= f.label :image %>
                <%= f.file_field :image %>
              </p>

              <%= f.submit 'Upload' %>
              <%= button_to 'Cancel', home_path(), :class => "button medium", :method => :get %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="col-md-12" style="margin-top:100px">
    <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
			<%= link_to user.name, user %>
        </div>
      </div>
    </div>

</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <ul>
        <div class="col-md-12" style="margin-top:100px">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <% @users.each do |user| %>
                    <% if current_user.id != user.id %>
                      <p><%= link_to user.name, user %></p>
                    <% end %>
                  <% end %>
                </div>
              </div>
          </div>
        </div>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="col-md-12" style="margin-top:100px">
    <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
          	<center>
				<h3> <%= @user.name %>'s Profile </h3>
				<p>Name: <%= @user.name if @user.name %></p>
				<p>Join Date: <%= @user.created_at.strftime("%m/%d/%Y") if @user.created_at %></p>
				<p>Posts:
					<% if @user.posts.empty? %>
						User has not uploaded any photos :(
					<% end %>
					<% @user.posts.reverse.each do |p| %>
					<ul>
						<% if p != NIL %>
							<%= render p %>
						<% end %>
					</ul>
					<h4>Add a comment:</h4>
		            <%= form_for([p, p.comments.build]) do |f| %>
		              <div class="field">
		                <%= f.label :body %><br />
		                <%= f.text_area :body %>
		              </div>
		              <div class="actions">
		                <%= f.submit %>
		              </div>
		            <% end %>
		            <br/>
		          <% if p.comments.first.body == NIL %>
		          <h4>Comments:</h4>
		          <p> No comments yet :( </p>
		          <% else %>
		          <h4>Comments:</h4>
		          <% p.comments.each do |comment| %>
		              <%if comment.commenter != NIL %>
		              <h6>
		                <b><%= comment.commenter %> says:</b>
		                "<%= comment.body %>"
		              </h6>
		              <%end%>
		          <% end %>
		          <% end %>
					<% end %>
			</center>
        </div>
    </div>
  </div>
</div>